### ISSUE TITLE
Invoke animation fave-button during viewDidLoad?

### ISSUE THREAD

**Issue by tuantmtb** [xhamr/fave-button#1]
I want to invoke animation fave-button during viewDidLoad
I found a solution.
**At library fave-button.**
func animateSelect (line:177)
Change private ->public
**At viewController**
call FaveButton.animateSelect(true, duration: Double)
It work!

So I want library change scope function  animateSelect: private -> public
Thank you!

**Comment by janselv** [comment]
Hi @tuantmtb, have you tried to set the `selected` property on FaveButton ?

`faveButton.selected = true` 

is the same as calling the method `FaveButton.animateSelect`
