### ISSUE TITLE
Why the button color is always grey color?

### ISSUE THREAD

**Issue by samad5353** [xhamr/fave-button#13]
I want to use custom colors in button but first time its showing grey color .  the attached image is white in color but its converting that to grayscale.

![screen shot 2016-12-29 at 11 56 13 am](https://cloud.githubusercontent.com/assets/13150747/21539284/cb14239c-cdbe-11e6-93cc-fb27dfd024d3.png)

**Comment by janselv** [comment]
If you're trying to change the default gray color by a custom one, have you try to set the property `normalColor` either via storyboard or code ?

**Comment by londonbridges13** [comment]
I'm having the same problem and that doesn't work.

**Comment by londonbridges13** [comment]
What work for me was setting the isSelected

**Comment by samad5353** [comment]
@xhamr i tried with normal color its not working for the first time. Only working after a click is performed, Initially it will be grayscale.

**Comment by xhamr** [comment]
@samad5353 can you attach an image of how the button looks like after the click ?

**Comment by jm3ndoza** [comment]
@samad5353 I overcame this by subclassing it and setting the _isSelected_ property to _false_ in the _awakeFromNib_ method which set it to its correct normal colour.

**Comment by samad5353** [comment]
@jm3ndoza Thanks it worked for me 👍
