### ISSUE TITLE
Selection with no animation

### ISSUE THREAD

**Issue by toseefkhilji** [xhamr/fave-button#14]
In my view there is favourite button. I want to set favbutton as selected.

So i have write this in viewDidLoad:
`favButton.isSelected = true`

but it shows animations when my view is loading.

I only want animations on favButton tap.

So is there any method for setting selected behaviour without animation? or how can achieve this?

**Comment by almatri** [comment]
same issue with me , I have table with cells having faveButton. 
I set the favButton to selected (if the cell belongs to favorites array) in the cellForRowAtindexPath delegate 

And it is very annoying to see the favButton animate while I scrolling the table.

so please allow us to disable the animation .

**Comment by okipol88** [comment]
Hi All,

I added a pull request with the possibility to do just that - change the selection without animation.

https://github.com/xhamr/fave-button/pull/19

**Comment by FranciscoMkdir** [comment]
How?

**Comment by uknowmeright** [comment]
please merge this into Master branch. Thank you.

**Comment by eclair4151** [comment]
for anyone who doesn't mind pulling directly off of @okipol88  branch you can do this

in your pod file
pod 'FaveButton', :git => 'https://github.com/okipol88/fave-button', :branch => 'feature/selectionWithoutAnimation'


then in your code 
myButton.setSelected(selected: true, animated: false)

**Comment by yarodevuci** [comment]
@eclair4151 hey, can you update to SWIFT 4

**Comment by s2mr** [comment]
I have published repository merge without animation and migrating to swift4.
https://github.com/kzumu/fave-button

**Comment by janselv** [comment]
Solved by merging @okipol88 pull request [#19](https://github.com/xhamr/fave-button/pull/19)
