### ISSUE TITLE
Support for swift 4.0?

### ISSUE THREAD

**Issue by fsufyan** [xhamr/fave-button#43]
Hi

the latest version doesn't seem to support Swift 4.0
I get an error in FaveButton.swift indicating:
'init(colorLiteralRed:green:blue:alpha:)' is unavailable: This initializer is only meant to be used by color literals

This can be solved by replacing colorLiteralRed to **red** and toggle func() to be preceded by @objc

If you would like i can submit a Pull Request.

**Comment by janselv** [comment]
Swift 4.2 supported with patch #46
