### ISSUE TITLE
Is fave-button's size fixed?

### ISSUE THREAD

**Issue by muratyasarr** [xhamr/fave-button#5]
It seems that I cannot change the size of the fave-button. Is it possible to make the size the same as the imageView's size?

**Comment by janselv** [comment]
Thanks @muratyasarr, If you're using `storyboard` to place a button, the size of the `fave-button` is based on the size you specify for it, for manual creation is based on the frame you pass to it at creation. Yo can see that in the demo app, where bottom and center buttons have different dimensions.
